---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command:
            [
              'sh',
              '-c',
              'echo -e "Checking for the availability of Postgres Server deployment"; while ! nc -z postgres-service 5432; do sleep 1; printf "-"; done; echo -e "  >> Postgres DB Server has started";',
            ]
      containers:
        - name: backend
          image: mailingapp.azurecr.io/backendapp/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: db_username
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: db_name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db_port
            - name: JWT_ACCESS_TTL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: token_ttl
            - name: WHITELISTDOMAINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: white_list_domains
            - name: EMAIL_DISABLED_PRODUCTS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: email_domains_disabled
            - name: MAILING_LABEL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mailing_label_endpoint
            - name: TRACKING_LABEL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: tracking_label_endpoint
            - name: USPS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: usps_username
            - name: USPS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: usps_password
            - name: SENDER_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: sender_name
            - name: SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: sender_email
            - name: MAILGUN_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mailgun_api_key
            - name: MAILGUN_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mailgun_domain
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: node_env
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: basic_auth_password
            - name: AUTH_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: auth_api_key
            - name: EASY_POST_CLINET_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: easy_post_client_key
            - name: XPS_CONNECT_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: xps_connect_api_key
            - name: XPS_CONNECT_CUSTOMER_ID
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: xpx_connect_customer_id
            - name: FTP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ftp_hostname
            - name: FTP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ftp_username
            - name: FTP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ftp_password
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-db-password
                  key: db_password
            - name: JWT_SECRETE
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: token_secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      targetPort: 8000
      port: 80
