---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mailingapp.azurecr.io/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_MAILING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: frontend-admin-config
                  key: backend_url
            - name: REACT_APP_TOKEN_FIELD
              valueFrom:
                configMapKeyRef:
                  name: frontend-admin-config
                  key: token_field
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      targetPort: 80
      port: 80
