apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailing-app-ingress-service
spec:
  ingressClassName: nginx
  rules:
    - host: frontend.ibrarmunir.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: admin.ibrarmunir.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 80
    - host: api.ibrarmunir.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
