apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-sc
  resources:
    requests:
      storage: 5Gi
